Added style for institution-list page
joisemp/sfs-busnest pull request #20
Opened 2024-11-12 10:20 UTC by kumkum671

# Checklist
- [X] This PR targets the `main` branch. 
- [X] The commit message is written in past tense.
- [ ] I have added or updated relevant **tests**.
- [ ] I have added or updated relevant **docs**, including release notes if applicable.
- [X] For UI changes, I have attached **screenshots**

![image](https://github.com/user-attachments/assets/0ac229b8-7fc5-4bbb-a257-ef63be921f5e)

2024-11-13 08:20 UTC, joisemp requested changes
Make the changes mentioned

2024-11-13 08:20 UTC, joisemp commented on src/static/styles/central_admin/institution_list/style.scss
> +        max-width:18rem;
When screen size max width is 767px give max-width 100%

![image](https://github.com/user-attachments/assets/4f7584af-af74-4462-ab8f-26a45f16b116)

2024-11-15 11:19 UTC, kumkum671 commented on src/static/styles/central_admin/institution_list/style.scss
> +        max-width:18rem;
resolved issue

2024-11-15 11:27 UTC, kumkum671 commented
solved the card issue  [here](https://github.com/joisemp/sfs-busnest/pull/20/commits/0632a57f394643270420e2690306215d3b0f7266)

![image](https://github.com/user-attachments/assets/d53e165f-fb7c-4c5a-87e1-0908fd0d508c)

2024-11-17 09:26 UTC, joisemp approved these changes
Good to merge. However, may need few code formatting later.

2024-11-17 09:26 UTC, joisemp commented on src/static/styles/central_admin/institution_list/style.scss
> +        max-width:18rem;
Perfect

2024-11-17 09:57 UTC, merged